In [1]:
import gymnasium as gym
import os, sys

current_dir = os.getcwd()
parent_dir = os.path.dirname(current_dir)
sys.path.append(parent_dir)

from models.dqn import DQN_Agent
import torch

In [2]:
train_env = gym.make("ALE/Pong-v5", render_mode=None)
test_env = gym.make("ALE/Pong-v5", render_mode="human")

A.L.E: Arcade Learning Environment (version 0.8.1+53f58b7)
[Powered by Stella]


In [4]:
model = DQN_Agent(n_observations=(210,160,3), n_actions=6, big_net=True, cnn=True,
                  double_network=True, tau=1e-2, batch_size=128, lr=1e-4, eps_decay=0.9999)

In [5]:
def train_model(model, n_games):
    for game in range(n_games):
        done = False
        obs, _ = train_env.reset()
        sum_reward = 0
        episode_length=0

        while not done:
            action = model.learning_act(obs)
            new_obs, reward, done,_, _ = train_env.step(action)
            model.store_memory(obs, new_obs, action, reward, done)

            model.learn()
            obs = new_obs

            sum_reward += reward
            episode_length += 1

        print(game, ": ", sum_reward)

In [6]:
def evaluate_model(model, n_games):
    for _ in range(n_games):
        done = False
        observation, _ = test_env.reset()
        sum_reward = 0
        while not done:            
            action = model.act(observation)
            print(action)
            observation, reward, done, _, _ = test_env.step(action)
            sum_reward += reward
        print(f"{n_games}th game: {sum_reward}")

In [7]:
train_model(model=model, n_games=100)
torch.save(model.policy_network.state_dict(), "../weights/pong_ram.pt")

ValueError: could not broadcast input array from shape (210,160,3) into shape (128,)

In [ ]:
evaluate_model(model=model, n_games=5)

[60.381992 60.875885 60.934784 57.541702 60.502083 59.828083]
2
[60.15494  60.625275 60.349895 57.31604  60.10923  60.20113 ]
1
[59.633175 60.312714 59.840015 56.61386  59.57749  59.905567]
1
[59.56777  60.238495 59.71508  56.53363  59.496223 59.844257]
1
[59.564205 60.230255 59.662617 56.51906  59.48829  59.83724 ]
1
[59.581505 60.243256 59.62546  56.52643  59.50477  59.84902 ]
1
[59.59885  60.2565   59.58829  56.533813 59.521248 59.86095 ]
1
[59.616215 60.269867 59.55108  56.54123  59.537727 59.872883]
1
[59.633533 60.283173 59.513905 56.548676 59.554268 59.884663]
1
[59.650944 60.296295 59.476704 56.556076 59.570747 59.896748]
1
[59.668262 60.30954  59.439514 56.56346  59.587227 59.90859 ]
1
[59.685593 60.322784 59.40234  56.570847 59.603737 59.92055 ]
1
[59.702908 60.33603  59.365173 56.57823  59.620247 59.93233 ]
1
[59.720276 60.349274 59.32798  56.585648 59.636696 59.944233]
1
[59.73759  60.36264  59.290783 56.593033 59.653267 59.956165]
1
[63.12886  63.086884 61.96235  60.478195

KeyboardInterrupt: 